using System;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using System.Threading;
using System.Collections.Generic;

namespace RemoveLandscapeVertexColor {
    public class Program {
        public static Lazy<Settings> _settings = null!;
        public static Settings settings => _settings.Value;

        private static readonly List<string> log = new();
        public static async Task<int> Main(string[] args) {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "RemoveLandscapeVertexColor.esp")
                .Run(args);
        }

        public static object myLock = new();

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state) {
            settings.Compile();
            var contextArray = state.LoadOrder.PriorityOrder.Landscape().WinningContextOverrides(state.LinkCache);
            var size = contextArray.Count();
            int skipCounter = 0;
            int removeCounter = 0;
            int failCounter = 0;
            int progressCounter = 0;
            var patchMod = state.PatchMod;
            Parallel.ForEach(contextArray, new ParallelOptions() {
                MaxDegreeOfParallelism = 8,
            }, (context) => {
                Console.WriteLine("Patch: " + Interlocked.Increment(ref progressCounter) + "/" + size);
                var landscapeGetter = context.Record;
                bool hasVertexColor = false;
                try {
                    if((landscapeGetter.DATA!.Value[0] & 2) == 2) {
                        hasVertexColor = true;
                    } else {
                        Interlocked.Increment(ref skipCounter);
                    }
                } catch(Exception) {
                    var message = "Could not parse landscape record: " + landscapeGetter.FormKey;
                    lock(myLock) {
                        log.Add(message);
                    }
                    Interlocked.Increment(ref failCounter);
                }
                if(hasVertexColor) {
                    ILandscape landscape;
                    lock(myLock) {
                        landscape = context.GetOrAddAsOverride(patchMod);
                    }
                    if(settings.removeAllVertexVertexColors) {
                        var data = landscape.DATA!.Value.ToArray();
                        data[0] &= 253;
                        landscape.DATA = new Noggog.MemorySlice<byte>(data);
                        landscape.VertexColors = null;
                    } else {
                        var grid = new LandscapeGrid(landscape);
                        grid.Patch(state);
                    }

                    Interlocked.Increment(ref removeCounter);

                }
            });
            Console.WriteLine(removeCounter + " landscape records had their vertex colors patched.");
            Console.WriteLine(skipCounter + " landscape records were skipped, because they had no vertex colors.");
            Console.WriteLine(failCounter + " landscape records were skipped, because there were errors parsing the records.");

            if(log.Count > 0) {
                foreach(var str in log) {
                    Console.WriteLine(str);
                }
            }
        }
    }
}
